workflows:
  ios-dev-client:
    name: iOS Dev Client (Clean Build)

    instance_type: mac_mini_m2

    environment:
      xcode: latest
      node: latest

    scripts:
      - name: Install JS dependencies
        script: |
          npm install

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update

      - name: Clean iOS build folder
        script: |
          cd ios
          xcodebuild clean -workspace VolleyballTrainerPro.xcworkspace -scheme VolleyballTrainerPro

      - name: Archive iOS App
        script: |
          cd ios
          xcodebuild \
            -workspace VolleyballTrainerPro.xcworkspace \
            -scheme VolleyballTrainerPro \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/VolleyballTrainerPro.xcarchive \
            clean archive \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=2G78XY4X97 \
            PROVISIONING_PROFILE_SPECIFIER="VolleyballTrainerPro AdHoc" \
            -allowProvisioningUpdates

      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/VolleyballTrainerPro.xcarchive \
            -exportPath $CM_BUILD_DIR/ipa \
            -exportOptionsPlist ios/ExportOptions.plist

    artifacts:
      - ipa/*.ipa
