require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

platform :ios, '14.0'

install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

flipper_config = FlipperConfiguration.disabled

target 'VolleyballTrainerPro' do
  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  #
  # 🚫 Removed: use_expo_modules!
  # This project is no longer using Expo modules.
  #

  # --- Boost override for RN 0.73 ---
  boost_podspec_path = File.join(__dir__, "../node_modules/react-native/third-party-podspecs/boost.podspec")
  File.open(boost_podspec_path, "w") do |f|
    f.write <<~RUBY
      Pod::Spec.new do |s|
        s.name     = "boost"
        s.version  = "1.83.0"
        s.summary  = "Boost C++ Libraries"
        s.homepage = "https://www.boost.org"
        s.license  = { :type => "Boost Software License", :file => "LICENSE" }
        s.authors  = "Boost Contributors"
        s.source   = {
          :http    => "https://sourceforge.net/projects/boost/files/boost/1.83.0/boost_1_83_0.tar.bz2",
          :sha256  => "6478edfe2f3305127cffe8caf73ea0176c53769f4bf1585be237eb30798c3b8e"
        }
        s.requires_arc = false
        s.header_mappings_dir = "boost"
        s.source_files = "boost/**/*.{h,hpp}"
      end
    RUBY
  end

  # --- React Native 0.73 + Hermes ---
  use_react_native!(
    :path => "../node_modules/react-native",
    :hermes_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :flipper_configuration => flipper_config
  )

  # --- Native ML pods ---
  pod 'MediaPipeTasksVision'
  pod 'MLModels', :path => '../MLModels'


  # --- Custom native modules ---
  pod 'MLBridge', :path => '../ios/MLBridge'
  pod 'ReplayKitRecorder', :path => '../ios/ReplayKitRecorder'

  post_install do |installer|
    react_native_post_install(
      installer,
      :mac_catalyst_enabled => false
    )

    # Disable signing for resource bundles
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
        target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
          resource_bundle_target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          end
        end
      end
  end
end

