// training/trainingLibrary.ts

export type TrainingCategory =
  | 'stretching'
  | 'plyometrics'
  | 'strength'
  | 'agility'
  | 'conditioning'
  | 'volleyballHitting'
  | 'break';

export type TrainingIntensity = 'low' | 'moderate' | 'high';

export type TrainingBlock = {
  id: string;
  name: string;
  category: TrainingCategory;
  intensity: TrainingIntensity;
  durationMinutes: number;
  image: any;              // PNG you’ll create
  instructions: string[];
};

export const TRAINING_LIBRARY: TrainingBlock[] = [
  {
    id: 'stretch-full-body-1',
    name: 'Full-Body Dynamic Stretch',
    category: 'stretching',
    intensity: 'low',
    durationMinutes: 3,
    image: require('../assets/images/training/stretch_full_body.png'),
    instructions: [
      'Jog lightly in place for 60 seconds.',
      'Leg swings front-to-back and side-to-side, 10 each leg.',
      'Arm circles small to large, 20 seconds each direction.',
      'Hip circles and trunk rotations, 30 seconds each.',
    ],
  },
  {
  id: 'stretch-hip-mobility-1',
  name: 'Dynamic Hip Mobility Flow',
  category: 'stretching',
  intensity: 'low',
  durationMinutes: 3,
  image: require('../assets/images/training/stretch_hip_mobility.png'),
  instructions: [
    'Perform alternating knee hugs for 30 seconds.',
    'Transition into walking lunges with rotation, 10 each side.',
    'Add lateral lunges, 10 each direction.',
    'Finish with hip openers (inward/outward circles), 20 seconds each leg.',
  ],
},
{
  id: 'stretch-shoulder-prep-1',
  name: 'Shoulder & Scapular Prep',
  category: 'stretching',
  intensity: 'low',
  durationMinutes: 3,
  image: require('../assets/images/training/stretch_shoulder_prep.png'),
  instructions: [
    'Perform band pull-aparts: 15 reps.',
    'Scapular wall slides: 10 slow reps.',
    'Arm circles small-to-large: 20 seconds each direction.',
    'Finish with overhead reaches and side bends: 30 seconds.',
  ],
},
{
  id: 'stretch-leg-prep-1',
  name: 'Dynamic Leg Prep',
  category: 'stretching',
  intensity: 'low',
  durationMinutes: 3,
  image: require('../assets/images/training/stretch_leg_prep.png'),
  instructions: [
    'High knees for 20 seconds.',
    'Butt kicks for 20 seconds.',
    'Leg swings front/back and lateral, 10 each.',
    'Walking toe touches for 2 passes.',
  ],
},
{
  id: 'stretch-tspine-1',
  name: 'Thoracic Spine Warm-Up',
  category: 'stretching',
  intensity: 'low',
  durationMinutes: 3,
  image: require('../assets/images/training/stretch_tspine.png'),
  instructions: [
    'Cat-cow: 30 seconds.',
    'Thread-the-needle: 8 reps each side.',
    'Open-book rotations: 10 each side.',
    'Finish with standing trunk rotations: 30 seconds.',
  ],
},
{
  id: 'stretch-ankle-activation-1',
  name: 'Ankle & Foot Activation',
  category: 'stretching',
  intensity: 'low',
  durationMinutes: 3,
  image: require('../assets/images/training/stretch_ankle_activation.png'),
  instructions: [
    'Ankle circles: 20 seconds each direction.',
    'Toe raises: 15 reps.',
    'Heel walks: 20 meters.',
    'Toe walks: 20 meters.',
  ],
},
{
  id: 'stretch-court-run-1',
  name: 'Full Court Warm-Up Run',
  category: 'stretching',
  intensity: 'low',
  durationMinutes: 3,
  image: require('../assets/images/training/stretch_court_run.png'),
  instructions: [
    'Jog baseline to baseline twice.',
    'Side shuffle down and back each direction.',
    'Backpedal down, jog forward back.',
    'Finish with 3 controlled accelerations to midcourt.',
  ],
},
{
  id: 'stretch-hamstring-dynamic-1',
  name: 'Dynamic Hamstring Prep',
  category: 'stretching',
  intensity: 'low',
  durationMinutes: 3,
  image: require('../assets/images/training/stretch_hamstring_dynamic.png'),
  instructions: [
    'Walking toe touches: 2 passes.',
    'A-skips: 20 seconds.',
    'Straight-leg bounds: 10 each leg.',
    'Standing hamstring sweeps: 10 each side.',
  ],
},
{
  id: 'stretch-prejump-1',
  name: 'Pre-Jump Warm-Up',
  category: 'stretching',
  intensity: 'low',
  durationMinutes: 3,
  image: require('../assets/images/training/stretch_prejump.png'),
  instructions: [
    'Mini pogo hops: 20 seconds.',
    'Quarter squat pulses: 15 reps.',
    'Calf bounces: 20 seconds.',
    'Hip hinge warm-up: 10 slow reps.',
  ],
},
{
  id: 'stretch-vb-flow-1',
  name: 'Volleyball Warm-Up Flow',
  category: 'stretching',
  intensity: 'low',
  durationMinutes: 3,
  image: require('../assets/images/training/stretch_vb_flow.png'),
  instructions: [
    'Arm swings forward/backward: 20 seconds.',
    'Approach footwork walk-through: 2 passes.',
    'Light jumps with soft landing: 10 reps.',
    'Hip and shoulder mobility rotations: 30 seconds.',
  ],
},
{
  id: 'stretch-balance-1',
  name: 'Dynamic Balance & Stability Warm-Up',
  category: 'stretching',
  intensity: 'low',
  durationMinutes: 3,
  image: require('../assets/images/training/stretch_balance.png'),
  instructions: [
    'Single-leg balance with arm reach: 20 seconds each.',
    'Single-leg hinge touches: 8 each side.',
    'Lateral step-and-hold: 10 each direction.',
    'Finish with controlled ankle mobility: 30 seconds.',
  ],
},
{
  id: 'agility-ladder-2',
  name: 'Ladder Lateral Quick Steps',
  category: 'agility',
  intensity: 'moderate',
  durationMinutes: 8,
  image: require('../assets/images/training/agility_ladder_lateral.png'),
  instructions: [
    'Face sideways to the ladder.',
    'Step in-in-out-out through each box.',
    'Perform 3 passes each direction.',
    'Keep hips low and steps light.',
  ],
},
{
  id: 'agility-ladder-3',
  name: 'Icky Shuffle Ladder Drill',
  category: 'agility',
  intensity: 'moderate',
  durationMinutes: 8,
  image: require('../assets/images/training/agility_icky_shuffle.png'),
  instructions: [
    'Step into the first box with one foot.',
    'Bring the second foot in, then step out laterally.',
    'Repeat rhythm down the ladder.',
    'Perform 3–4 passes.',
  ],
},
{
  id: 'agility-ladder-4',
  name: 'Ladder Hopscotch Drill',
  category: 'agility',
  intensity: 'moderate',
  durationMinutes: 7,
  image: require('../assets/images/training/agility_hopscotch.png'),
  instructions: [
    'Jump feet together into the box.',
    'Jump feet apart outside the next box.',
    'Continue alternating for 2–3 passes.',
    'Focus on soft landings and rhythm.',
  ],
},
{
  id: 'agility-ladder-5',
  name: 'Ladder Single-Leg Hops',
  category: 'agility',
  intensity: 'high',
  durationMinutes: 6,
  image: require('../assets/images/training/agility_single_leg_hops.png'),
  instructions: [
    'Hop through the ladder on one leg.',
    'Switch legs on the return pass.',
    'Perform 2 passes each leg.',
    'Maintain balance and quick contacts.',
  ],
},
{
  id: 'agility-cone-1',
  name: 'Cone T-Drill',
  category: 'agility',
  intensity: 'high',
  durationMinutes: 10,
  image: require('../assets/images/training/agility_t_drill.png'),
  instructions: [
    'Sprint forward to the center cone.',
    'Shuffle right, then left, then back to center.',
    'Backpedal to the start.',
    'Perform 4–6 reps with control.',
  ],
},
{
  id: 'agility-cone-2',
  name: 'Cone 5-10-5 Shuttle',
  category: 'agility',
  intensity: 'high',
  durationMinutes: 8,
  image: require('../assets/images/training/agility_5_10_5.png'),
  instructions: [
    'Start in athletic stance.',
    'Sprint 5 yards right, then 10 left, then 5 right.',
    'Touch the line each change of direction.',
    'Perform 4–6 reps.',
  ],
},
{
  id: 'agility-cone-3',
  name: 'Cone Box Shuffle',
  category: 'agility',
  intensity: 'moderate',
  durationMinutes: 9,
  image: require('../assets/images/training/agility_box_shuffle.png'),
  instructions: [
    'Set 4 cones in a square.',
    'Shuffle around the square clockwise.',
    'Repeat counterclockwise.',
    'Perform 3 rounds each direction.',
  ],
},
{
  id: 'agility-cone-4',
  name: 'Zig-Zag Sprint Drill',
  category: 'agility',
  intensity: 'high',
  durationMinutes: 7,
  image: require('../assets/images/training/agility_zigzag.png'),
  instructions: [
    'Place cones in a zig-zag pattern.',
    'Sprint diagonally cone to cone.',
    'Focus on sharp cuts and low hips.',
    'Perform 3–4 passes.',
  ],
},
{
  id: 'agility-cone-5',
  name: 'Figure-8 Acceleration Drill',
  category: 'agility',
  intensity: 'moderate',
  durationMinutes: 8,
  image: require('../assets/images/training/agility_figure8.png'),
  instructions: [
    'Set two cones 10 feet apart.',
    'Run in a figure-8 pattern around both cones.',
    'Stay tight to the cones and accelerate out of turns.',
    'Perform 4–6 rounds.',
  ],
},
{
  id: 'agility-reaction-1',
  name: 'Partner Reaction Shuffle',
  category: 'agility',
  intensity: 'moderate',
  durationMinutes: 6,
  image: require('../assets/images/training/agility_reaction_shuffle.png'),
  instructions: [
    'Face your partner in athletic stance.',
    'Partner points left or right.',
    'Shuffle quickly in that direction.',
    'Perform 20–30 rapid cues.',
  ],
},
{
  id: 'agility-reaction-2',
  name: 'Ball Drop Reaction Sprint',
  category: 'agility',
  intensity: 'high',
  durationMinutes: 6,
  image: require('../assets/images/training/agility_ball_drop.png'),
  instructions: [
    'Partner holds a ball at shoulder height.',
    'Sprint forward and catch the ball before it bounces twice.',
    'Reset and repeat for 8–10 reps.',
    'Focus on explosive first step.',
  ],
},
{
  id: 'agility-reaction-3',
  name: 'Color Cone Reaction Drill',
  category: 'agility',
  intensity: 'moderate',
  durationMinutes: 7,
  image: require('../assets/images/training/agility_color_cone.png'),
  instructions: [
    'Set cones of different colors around you.',
    'Partner calls a color.',
    'Sprint or shuffle to that cone.',
    'Perform 12–15 cues.',
  ],
},
{
  id: 'agility-court-1',
  name: 'Baseline to Net Shuffle',
  category: 'agility',
  intensity: 'moderate',
  durationMinutes: 8,
  image: require('../assets/images/training/agility_baseline_net.png'),
  instructions: [
    'Start at baseline.',
    'Shuffle to the net and back.',
    'Stay low and maintain speed.',
    'Perform 6–8 reps.',
  ],
},
{
  id: 'agility-court-2',
  name: 'Court Perimeter Sprint',
  category: 'agility',
  intensity: 'high',
  durationMinutes: 9,
  image: require('../assets/images/training/agility_court_perimeter.png'),
  instructions: [
    'Sprint around the court boundary.',
    'Touch each corner.',
    'Perform 3–4 laps.',
    'Maintain consistent pace.',
  ],
},
{
  id: 'agility-court-3',
  name: 'Short-to-Long Acceleration',
  category: 'agility',
  intensity: 'high',
  durationMinutes: 7,
  image: require('../assets/images/training/agility_short_long.png'),
  instructions: [
    'Sprint 5 yards, stop, then 10 yards, stop.',
    'Repeat for 3–4 rounds.',
    'Focus on explosive starts.',
  ],
},
{
  id: 'agility-court-4',
  name: 'Lateral Court Slides',
  category: 'agility',
  intensity: 'moderate',
  durationMinutes: 8,
  image: require('../assets/images/training/agility_lateral_slides.png'),
  instructions: [
    'Slide sideline to sideline.',
    'Touch each line with your hand.',
    'Perform 4–6 rounds.',
    'Keep chest up and hips low.',
  ],
},
{
  id: 'agility-court-5',
  name: 'Net-to-Sideline Shuttle',
  category: 'agility',
  intensity: 'moderate',
  durationMinutes: 7,
  image: require('../assets/images/training/agility_net_sideline.png'),
  instructions: [
    'Start at the net.',
    'Shuffle to sideline, backpedal to net.',
    'Repeat opposite direction.',
    'Perform 3–4 rounds.',
  ],
},
{
  id: 'agility-multi-1',
  name: '4-Corner Multi-Direction Drill',
  category: 'agility',
  intensity: 'high',
  durationMinutes: 9,
  image: require('../assets/images/training/agility_4_corner.png'),
  instructions: [
    'Set 4 cones in a square.',
    'Sprint forward, shuffle right, backpedal, shuffle left.',
    'Repeat for 4–6 rounds.',
  ],
},
{
  id: 'agility-multi-2',
  name: 'Diagonal Crossover Steps',
  category: 'agility',
  intensity: 'moderate',
  durationMinutes: 8,
  image: require('../assets/images/training/agility_crossover.png'),
  instructions: [
    'Set cones diagonally across the court.',
    'Perform crossover steps cone to cone.',
    'Keep shoulders square and steps sharp.',
    'Perform 3–4 passes.',
  ],
},
{
  id: 'agility-multi-3',
  name: 'Sprint–Shuffle–Backpedal Combo',
  category: 'agility',
  intensity: 'high',
  durationMinutes: 8,
  image: require('../assets/images/training/agility_combo.png'),
  instructions: [
    'Sprint forward 10 feet.',
    'Shuffle right 10 feet.',
    'Backpedal to start.',
    'Repeat for 6–8 rounds.',
  ],
},
{
  id: 'plyo-squat-jumps-1',
  name: 'Squat Jump Repeats',
  category: 'plyometrics',
  intensity: 'high',
  durationMinutes: 6,
  image: require('../assets/images/training/plyo_squat_jumps.png'),
  instructions: [
    'Perform an athletic squat and explode upward.',
    'Land softly and reset quickly.',
    'Complete 3 sets of 10 reps.',
    'Rest 45–60 seconds between sets.',
  ],
},
{
  id: 'plyo-lateral-hops-1',
  name: 'Lateral Line Hops',
  category: 'plyometrics',
  intensity: 'moderate',
  durationMinutes: 5,
  image: require('../assets/images/training/plyo_lateral_line.png'),
  instructions: [
    'Stand beside a line on the floor.',
    'Hop side-to-side rapidly for 20 seconds.',
    'Rest 20 seconds and repeat 4 rounds.',
    'Focus on quick ground contacts.',
  ],
},
{
  id: 'plyo-broad-jump-1',
  name: 'Standing Broad Jumps',
  category: 'plyometrics',
  intensity: 'high',
  durationMinutes: 7,
  image: require('../assets/images/training/plyo_broad_jump.png'),
  instructions: [
    'Start in a loaded squat position.',
    'Explosively jump forward as far as possible.',
    'Land softly and walk back to start.',
    'Perform 3 sets of 6 reps.',
  ],
},
{
  id: 'plyo-tuck-jumps-1',
  name: 'Tuck Jump Series',
  category: 'plyometrics',
  intensity: 'high',
  durationMinutes: 6,
  image: require('../assets/images/training/plyo_tuck_jumps.png'),
  instructions: [
    'Jump vertically and bring knees toward chest.',
    'Land softly and immediately jump again.',
    'Perform 3 sets of 8 reps.',
    'Keep chest tall and core tight.',
  ],
},
{
  id: 'plyo-split-jumps-1',
  name: 'Split Lunge Jumps',
  category: 'plyometrics',
  intensity: 'high',
  durationMinutes: 7,
  image: require('../assets/images/training/plyo_split_jumps.png'),
  instructions: [
    'Start in a lunge position.',
    'Jump and switch legs mid-air.',
    'Land softly and repeat.',
    'Perform 3 sets of 10 reps each leg.',
  ],
},
{
  id: 'plyo-pogo-1',
  name: 'Pogo Hops',
  category: 'plyometrics',
  intensity: 'moderate',
  durationMinutes: 5,
  image: require('../assets/images/training/plyo_pogo.png'),
  instructions: [
    'Bounce lightly on the balls of your feet.',
    'Keep knees slightly bent and stiff ankles.',
    'Hop continuously for 20 seconds.',
    'Repeat 4–5 rounds.',
  ],
},
{
  id: 'plyo-depth-drop-1',
  name: 'Depth Drops',
  category: 'plyometrics',
  intensity: 'moderate',
  durationMinutes: 6,
  image: require('../assets/images/training/plyo_depth_drop.png'),
  instructions: [
    'Step off a low box (not jump).',
    'Land softly in an athletic stance.',
    'Absorb force through hips and knees.',
    'Perform 3 sets of 6 reps.',
  ],
},
{
  id: 'plyo-depth-jump-1',
  name: 'Depth Jump to Vertical',
  category: 'plyometrics',
  intensity: 'high',
  durationMinutes: 7,
  image: require('../assets/images/training/plyo_depth_jump_vertical.png'),
  instructions: [
    'Step off a box and land softly.',
    'Immediately explode upward into a vertical jump.',
    'Perform 3 sets of 5 reps.',
    'Focus on minimal ground contact time.',
  ],
},
{
  id: 'plyo-lateral-bound-1',
  name: 'Lateral Bounds',
  category: 'plyometrics',
  intensity: 'high',
  durationMinutes: 8,
  image: require('../assets/images/training/plyo_lateral_bounds.png'),
  instructions: [
    'Jump sideways from one leg to the other.',
    'Stick the landing and stabilize.',
    'Perform 3 sets of 8 bounds each direction.',
  ],
},
{
  id: 'plyo-single-leg-hop-1',
  name: 'Single-Leg Forward Hops',
  category: 'plyometrics',
  intensity: 'high',
  durationMinutes: 6,
  image: require('../assets/images/training/plyo_single_leg_forward.png'),
  instructions: [
    'Hop forward on one leg for 10 meters.',
    'Walk back and switch legs.',
    'Perform 2–3 rounds each leg.',
  ],
},
{
  id: 'plyo-box-lateral-1',
  name: 'Lateral Box Step-Overs',
  category: 'plyometrics',
  intensity: 'moderate',
  durationMinutes: 7,
  image: require('../assets/images/training/plyo_box_lateral.png'),
  instructions: [
    'Stand beside a low box.',
    'Step over laterally with quick feet.',
    'Repeat for 20 seconds per round.',
    'Perform 4–5 rounds.',
  ],
},
{
  id: 'plyo-hurdle-hop-1',
  name: 'Mini-Hurdle Quick Hops',
  category: 'plyometrics',
  intensity: 'high',
  durationMinutes: 6,
  image: require('../assets/images/training/plyo_hurdle_hops.png'),
  instructions: [
    'Set up 4–6 mini hurdles.',
    'Hop quickly over each with minimal contact.',
    'Perform 3–4 passes.',
  ],
},
{
  id: 'plyo-hurdle-lateral-1',
  name: 'Lateral Hurdle Jumps',
  category: 'plyometrics',
  intensity: 'high',
  durationMinutes: 7,
  image: require('../assets/images/training/plyo_hurdle_lateral.png'),
  instructions: [
    'Stand sideways to the hurdles.',
    'Jump laterally over each hurdle.',
    'Land softly and continue rhythmically.',
    'Perform 3 passes each direction.',
  ],
},
{
  id: 'plyo-multi-direction-1',
  name: 'Multi-Directional Jump Matrix',
  category: 'plyometrics',
  intensity: 'high',
  durationMinutes: 8,
  image: require('../assets/images/training/plyo_jump_matrix.png'),
  instructions: [
    'Jump forward, backward, left, and right in sequence.',
    'Stick each landing before the next jump.',
    'Perform 3 sets of 12 jumps.',
  ],
},
{
  id: 'plyo-approach-jump-1',
  name: 'Volleyball Approach Jumps',
  category: 'plyometrics',
  intensity: 'high',
  durationMinutes: 10,
  image: require('../assets/images/training/plyo_approach_jump.png'),
  instructions: [
    'Perform a full 3- or 4-step approach.',
    'Explode upward with full arm swing.',
    'Land softly and reset.',
    'Perform 3 sets of 6–8 jumps.',
  ],
},
{
  id: 'plyo-rebound-jumps-1',
  name: 'Continuous Rebound Jumps',
  category: 'plyometrics',
  intensity: 'high',
  durationMinutes: 6,
  image: require('../assets/images/training/plyo_rebound.png'),
  instructions: [
    'Jump repeatedly with minimal ground contact.',
    'Keep jumps small and rhythmic.',
    'Perform 20-second rounds, 4–5 times.',
  ],
},
{
  id: 'plyo-diagonal-bounds-1',
  name: 'Diagonal Bounds',
  category: 'plyometrics',
  intensity: 'moderate',
  durationMinutes: 7,
  image: require('../assets/images/training/plyo_diagonal_bounds.png'),
  instructions: [
    'Bound diagonally forward off one leg.',
    'Land on the opposite leg and stabilize.',
    'Perform 3 sets of 8 bounds each direction.',
  ],
},
{
  id: 'plyo-box-depth-lateral-1',
  name: 'Depth Drop to Lateral Shuffle',
  category: 'plyometrics',
  intensity: 'high',
  durationMinutes: 8,
  image: require('../assets/images/training/plyo_depth_lateral.png'),
  instructions: [
    'Step off a box and land softly.',
    'Immediately shuffle laterally 10 feet.',
    'Reset and repeat for 6–8 reps.',
  ],
},
{
  id: 'plyo-ankle-stiffness-1',
  name: 'Ankle Stiffness Hops',
  category: 'plyometrics',
  intensity: 'moderate',
  durationMinutes: 5,
  image: require('../assets/images/training/plyo_ankle_stiffness.png'),
  instructions: [
    'Perform small, fast hops with minimal knee bend.',
    'Bounce on the balls of your feet.',
    'Perform 20 seconds on, 20 seconds off for 5 rounds.',
  ],
},
{
  id: 'plyo-vertical-reach-1',
  name: 'Vertical Reach Touches',
  category: 'plyometrics',
  intensity: 'high',
  durationMinutes: 7,
  image: require('../assets/images/training/plyo_vertical_reach.png'),
  instructions: [
    'Jump vertically and touch a target or wall mark.',
    'Reset quickly and repeat.',
    'Perform 3 sets of 8–10 jumps.',
  ],
},
{
  id: 'vhitting-approach-2',
  name: 'Approach Rhythm Walkthrough',
  category: 'volleyballHitting',
  intensity: 'low',
  durationMinutes: 8,
  image: require('../assets/images/training/hitting_approach_rhythm.png'),
  instructions: [
    'Practice 3-step or 4-step approach at 50% speed.',
    'Focus on timing and consistent stride length.',
    'Add arm swing mechanics without jumping.',
    'Perform 4–5 rounds of 6–8 reps.',
  ],
},
{
  id: 'vhitting-arm-swing-1',
  name: 'Arm Swing Mechanics Drill',
  category: 'volleyballHitting',
  intensity: 'moderate',
  durationMinutes: 7,
  image: require('../assets/images/training/hitting_arm_swing.png'),
  instructions: [
    'Stand in hitting stance facing the net.',
    'Practice bow-and-arrow arm position.',
    'Perform slow-to-fast arm swings with full reach.',
    'Complete 3 sets of 10 reps.',
  ],
},
{
  id: 'vhitting-wall-spike-1',
  name: 'Wall Spike Repetitions',
  category: 'volleyballHitting',
  intensity: 'moderate',
  durationMinutes: 10,
  image: require('../assets/images/training/hitting_wall_spike.png'),
  instructions: [
    'Stand 6–8 feet from a wall.',
    'Toss the ball and spike into the wall.',
    'Focus on wrist snap and contact height.',
    'Perform 3 sets of 12–15 reps.',
  ],
},
{
  id: 'vhitting-target-1',
  name: 'Target Hitting Corners',
  category: 'volleyballHitting',
  intensity: 'high',
  durationMinutes: 12,
  image: require('../assets/images/training/hitting_target_corners.png'),
  instructions: [
    'Place targets in deep corners of the court.',
    'Receive a toss or set and attack the target.',
    'Alternate corners each rep.',
    'Perform 3 sets of 8–10 swings.',
  ],
},
{
  id: 'vhitting-line-shot-1',
  name: 'Line Shot Precision',
  category: 'volleyballHitting',
  intensity: 'moderate',
  durationMinutes: 9,
  image: require('../assets/images/training/hitting_line_shot.png'),
  instructions: [
    'Set up on the outside hitting position.',
    'Focus on hitting down the line with control.',
    'Use a controlled approach and full extension.',
    'Perform 3 sets of 8 reps.',
  ],
},
{
  id: 'vhitting-cross-court-1',
  name: 'Cross-Court Power Hits',
  category: 'volleyballHitting',
  intensity: 'high',
  durationMinutes: 10,
  image: require('../assets/images/training/hitting_cross_court.png'),
  instructions: [
    'Start at left or right antenna.',
    'Approach and hit cross-court to deep corner.',
    'Emphasize hip rotation and shoulder alignment.',
    'Perform 3 sets of 8–10 swings.',
  ],
},
{
  id: 'vhitting-timing-1',
  name: 'Setter Timing Connection',
  category: 'volleyballHitting',
  intensity: 'moderate',
  durationMinutes: 12,
  image: require('../assets/images/training/hitting_timing.png'),
  instructions: [
    'Work with a setter to establish timing.',
    'Start with slow tempo sets.',
    'Progress to game-speed tempo.',
    'Perform 15–20 total reps.',
  ],
},
{
  id: 'vhitting-block-vision-1',
  name: 'Block Vision Awareness',
  category: 'volleyballHitting',
  intensity: 'moderate',
  durationMinutes: 10,
  image: require('../assets/images/training/hitting_block_vision.png'),
  instructions: [
    'Have a coach or teammate simulate a block.',
    'Practice reading blocker hands and spacing.',
    'Hit around or off the block.',
    'Perform 3 sets of 8 swings.',
  ],
},
{
  id: 'vhitting-tooling-1',
  name: 'Tooling the Block Drill',
  category: 'volleyballHitting',
  intensity: 'high',
  durationMinutes: 10,
  image: require('../assets/images/training/hitting_tool_block.png'),
  instructions: [
    'Aim for the blocker’s outside hand.',
    'Practice controlled aggressive swings.',
    'Reset quickly after each rep.',
    'Perform 3 sets of 6–8 reps.',
  ],
},
{
  id: 'vhitting-roll-shot-1',
  name: 'Roll Shot Technique',
  category: 'volleyballHitting',
  intensity: 'low',
  durationMinutes: 8,
  image: require('../assets/images/training/hitting_roll_shot.png'),
  instructions: [
    'Approach normally but reduce jump height.',
    'Use a soft wrist roll to place the ball.',
    'Aim for open court space.',
    'Perform 3 sets of 10 reps.',
  ],
},
{
  id: 'vhitting-tip-control-1',
  name: 'Controlled Tip Placement',
  category: 'volleyballHitting',
  intensity: 'low',
  durationMinutes: 7,
  image: require('../assets/images/training/hitting_tip_control.png'),
  instructions: [
    'Practice fingertip control over the net.',
    'Tip to short corners and middle gaps.',
    'Alternate between left and right hand.',
    'Perform 3 sets of 12 reps.',
  ],
},
{
  id: 'vhitting-back-row-1',
  name: 'Back-Row Attack Drill',
  category: 'volleyballHitting',
  intensity: 'high',
  durationMinutes: 12,
  image: require('../assets/images/training/hitting_back_row.png'),
  instructions: [
    'Start behind the 10-foot line.',
    'Approach and hit from Zone 6, 1, or 5.',
    'Focus on staying behind the line.',
    'Perform 3 sets of 8 swings.',
  ],
},
{
  id: 'vhitting-transition-1',
  name: 'Transition Off the Net',
  category: 'volleyballHitting',
  intensity: 'moderate',
  durationMinutes: 10,
  image: require('../assets/images/training/hitting_transition.png'),
  instructions: [
    'Start at the net, then transition to attack position.',
    'Receive a set and hit with full approach.',
    'Repeat for 10–12 reps per round.',
  ],
},
{
  id: 'vhitting-approach-angle-1',
  name: 'Approach Angle Variation',
  category: 'volleyballHitting',
  intensity: 'moderate',
  durationMinutes: 9,
  image: require('../assets/images/training/hitting_approach_angle.png'),
  instructions: [
    'Practice approaches from wide, narrow, and middle angles.',
    'Focus on footwork consistency.',
    'Hit controlled swings from each angle.',
    'Perform 3 rounds of 6 reps.',
  ],
},
{
  id: 'vhitting-quick-set-1',
  name: 'Quick Set Attack',
  category: 'volleyballHitting',
  intensity: 'high',
  durationMinutes: 10,
  image: require('../assets/images/training/hitting_quick_set.png'),
  instructions: [
    'Work with a setter on fast tempo sets.',
    'React quickly and jump explosively.',
    'Focus on early takeoff timing.',
    'Perform 3 sets of 8 reps.',
  ],
},
{
  id: 'vhitting-slide-1',
  name: 'Slide Attack Footwork',
  category: 'volleyballHitting',
  intensity: 'moderate',
  durationMinutes: 12,
  image: require('../assets/images/training/hitting_slide.png'),
  instructions: [
    'Practice slide footwork without a ball.',
    'Add arm swing and controlled jumps.',
    'Progress to full-speed slide attacks.',
    'Perform 3 sets of 6–8 reps.',
  ],
},
{
  id: 'vhitting-high-ball-1',
  name: 'High Ball Out-of-System Hit',
  category: 'volleyballHitting',
  intensity: 'high',
  durationMinutes: 12,
  image: require('../assets/images/training/hitting_high_ball.png'),
  instructions: [
    'Simulate out-of-system high sets.',
    'Use a high, powerful approach.',
    'Aim deep corners for consistency.',
    'Perform 3 sets of 8 swings.',
  ],
},
{
  id: 'vhitting-block-read-1',
  name: 'Reading the Block Drill',
  category: 'volleyballHitting',
  intensity: 'moderate',
  durationMinutes: 10,
  image: require('../assets/images/training/hitting_read_block.png'),
  instructions: [
    'Have blockers shift late or early.',
    'Practice adjusting mid-air.',
    'Hit seam, line, or cross based on read.',
    'Perform 12–15 total reps.',
  ],
},
{
  id: 'vhitting-approach-jump-2',
  name: 'Max Jump Contact Height',
  category: 'volleyballHitting',
  intensity: 'high',
  durationMinutes: 8,
  image: require('../assets/images/training/hitting_max_jump.png'),
  instructions: [
    'Perform full approach jumps without hitting.',
    'Reach as high as possible each rep.',
    'Focus on explosive takeoff.',
    'Perform 3 sets of 6 jumps.',
  ],
},
{
  id: 'vhitting-game-sim-1',
  name: 'Game-Speed Hitting Simulation',
  category: 'volleyballHitting',
  intensity: 'high',
  durationMinutes: 14,
  image: require('../assets/images/training/hitting_game_sim.png'),
  instructions: [
    'Receive random sets from different positions.',
    'React quickly and attack with purpose.',
    'Mix power swings, roll shots, and tips.',
    'Perform 15–20 total swings.',
  ],
},
  {
    id: 'plyo-box-1',
    name: 'Box Jumps & Stick Landing',
    category: 'plyometrics',
    intensity: 'high',
    durationMinutes: 8,
    image: require('../assets/images/training/plyo_box_jumps.png'),
    instructions: [
      'Use a safe box height appropriate for the athlete.',
      'Jump explosively onto the box, land softly in an athletic stance.',
      'Step down under control, do not jump off.',
      'Perform 3 sets of 8–10 reps with 60–90 seconds rest.',
    ],
  },
  {
    id: 'agility-ladder-1',
    name: 'Ladder Quick Feet Series',
    category: 'agility',
    intensity: 'moderate',
    durationMinutes: 10,
    image: require('../assets/images/training/agility_ladder.png'),
    instructions: [
      'Set up an agility ladder on a flat surface.',
      'Perform 2-feet-in-each box for 2 passes.',
      'Perform lateral in-and-out steps for 2 passes each direction.',
      'Keep hips low, eyes up, and quick ground contacts.',
    ],
  },
  {
    id: 'strength-core-1',
    name: 'Core Stability Circuit',
    category: 'stretching',
    intensity: 'moderate',
    durationMinutes: 5,
    image: require('../assets/images/training/core_stability.png'),
    instructions: [
      'Plank hold: 30–45 seconds.',
      'Side plank each side: 30 seconds.',
      'Dead bug: 10–12 reps each side.',
      'Repeat circuit 2–3 times with short rest.',
    ],
  },
  {
    id: 'vhitting-approach-1',
    name: 'Approach Footwork & Arm Swing',
    category: 'volleyballHitting',
    intensity: 'moderate',
    durationMinutes: 12,
    image: require('../assets/images/training/hitting_approach.png'),
    instructions: [
      'Practice 3-step or 4-step approach without ball, focusing on rhythm.',
      'Add arm swing mechanics with full reach and snap.',
      'Perform 3–4 sets of 8–10 controlled approaches.',
      'Emphasize consistent footwork and balanced landing.',
    ],
  },
];

// simple helper if you want generator later
export const totalMinutesOfBlocks = (blocks: TrainingBlock[]) =>
  blocks.reduce((sum, b) => sum + b.durationMinutes, 0);
