name: Upload IPA to TestFlight

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Fastlane
        run: sudo gem install fastlane -NV

      - name: Prepare API key file
        env:
          ASC_API_KEY: ${{ secrets.ASC_API_KEY }}
        run: |
          echo "$ASC_API_KEY" > api_key.p8

      - name: Upload IPA to TestFlight
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
        run: |
          fastlane deliver \
            --ipa "./dist/app.ipa" \
            --api-key api_key.p8 \
            --api-key-id "$ASC_KEY_ID" \
            --api-issuer "$ASC_ISSUER_ID" \
            --skip-screenshots \
            --skip-metadata
