name: Upload IPA to TestFlight

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Fastlane
        run: sudo gem install fastlane -NV

      - name: Prepare Fastlane API key JSON
        env:
          ASC_API_KEY: ${{ secrets.ASC_API_KEY }}
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
        run: |
          cat <<EOF > fastlane_api_key.json
          {
            "key_id": "${ASC_KEY_ID}",
            "issuer_id": "${ASC_ISSUER_ID}",
            "key": "${ASC_API_KEY}"
          }
          EOF

      - name: Upload IPA to TestFlight
        run: |
          fastlane deliver \
            --ipa "./dist/app.ipa" \
            --api-key fastlane_api_key.json \
            --skip-screenshots \
            --skip-metadata
